name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build
      
    - name: Configure repository secrets
      run: echo "::set-env name=VITE_GH_TOKEN::${{secrets.TIMELINE}}"

    - name: Check the environment variable
      run: |
        echo "VITE_GH_TOKEN=$VITE_GH_TOKEN"

    - name: Test API Request
      run: |
         response=$(curl -H "Authorization: token $VITE_GH_TOKEN" https://api.github.com/user)
         echo "API Response : ${response}"
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: dist
